# Site settings
title:          0x01BM
description:    "Benjamin Marr, Security Consultant from Edinburgh, Scotland."
url:            "https://marr.id"

# Author
author:
  name:         Benjamin Marr
  url:          https://marr.id
  email:        benjamin@marr.id

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  #- jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       10

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

